# Generated by Django 4.2 on 2026-04-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='processed_video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='processed/'),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='video_file',
            field=models.FileField(max_length=255, upload_to='uploads/'),
        ),
    ]
