# Generated by Django 4.2 on 2026-04-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation_app', '0002_alter_videoupload_processed_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='current_frame',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='estimated_seconds_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
